[package]
name = "robo-fill"
version = "0.1.0"
authors = ["Johan Backman <johback@student.chalmers.se>"]

[features]
default = []

[dependencies]
cgmath = "0.15"
clippy = {version = "*", optional = true}
ggez = "0.3"
specs = "0.9"
specs-derive = "0.1"
